
model:
  model_A: model
  model_cfg: model_cfg.yaml

training:
  dataset: BSD68

  max_epoch: 24
  batch_size: 4
  crop_size: [64, 64]
  aug: ['hflip', 'vflip', 'rot']

  init_lr: 1e-4
  loss: 1.*loss_type1+1e-4*loss_type2
  optimizer: SGD

validation:
  dataset: BSD68
  validation_start: 16
  imsave: True

output:
  checkpoint_interval_epoch: 1
  use_tensor_board: True
  log_interval_iter: 100
  log_file: True
  log_lvl: 
